// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="dataflow,hls_ip_2019_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=8.510000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=76,HLS_SYN_DSP=80,HLS_SYN_FF=11944,HLS_SYN_LUT=20404,HLS_VERSION=2019_2}" *)

module dataflow (
        s_axi_CTRL_BUS_AWVALID,
        s_axi_CTRL_BUS_AWREADY,
        s_axi_CTRL_BUS_AWADDR,
        s_axi_CTRL_BUS_WVALID,
        s_axi_CTRL_BUS_WREADY,
        s_axi_CTRL_BUS_WDATA,
        s_axi_CTRL_BUS_WSTRB,
        s_axi_CTRL_BUS_ARVALID,
        s_axi_CTRL_BUS_ARREADY,
        s_axi_CTRL_BUS_ARADDR,
        s_axi_CTRL_BUS_RVALID,
        s_axi_CTRL_BUS_RREADY,
        s_axi_CTRL_BUS_RDATA,
        s_axi_CTRL_BUS_RRESP,
        s_axi_CTRL_BUS_BVALID,
        s_axi_CTRL_BUS_BREADY,
        s_axi_CTRL_BUS_BRESP,
        ap_clk,
        ap_rst_n,
        interrupt,
        in_pixel0_TDATA,
        in_pixel0_TLAST,
        in_pixel1_TDATA,
        in_pixel1_TLAST,
        in_pixel2_TDATA,
        in_pixel2_TLAST,
        in_pixel3_TDATA,
        in_pixel3_TLAST,
        out_pixel0_TDATA,
        out_pixel0_TLAST,
        in_weight0_TDATA,
        in_weight0_TLAST,
        in_pixel0_TVALID,
        in_pixel0_TREADY,
        in_pixel1_TVALID,
        in_pixel1_TREADY,
        in_pixel2_TVALID,
        in_pixel2_TREADY,
        in_pixel3_TVALID,
        in_pixel3_TREADY,
        out_pixel0_TVALID,
        out_pixel0_TREADY,
        in_weight0_TVALID,
        in_weight0_TREADY
);

parameter    C_S_AXI_CTRL_BUS_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_BUS_ADDR_WIDTH = 7;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_S_AXI_ADDR_WIDTH = 32;

parameter C_S_AXI_CTRL_BUS_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   s_axi_CTRL_BUS_AWVALID;
output   s_axi_CTRL_BUS_AWREADY;
input  [C_S_AXI_CTRL_BUS_ADDR_WIDTH - 1:0] s_axi_CTRL_BUS_AWADDR;
input   s_axi_CTRL_BUS_WVALID;
output   s_axi_CTRL_BUS_WREADY;
input  [C_S_AXI_CTRL_BUS_DATA_WIDTH - 1:0] s_axi_CTRL_BUS_WDATA;
input  [C_S_AXI_CTRL_BUS_WSTRB_WIDTH - 1:0] s_axi_CTRL_BUS_WSTRB;
input   s_axi_CTRL_BUS_ARVALID;
output   s_axi_CTRL_BUS_ARREADY;
input  [C_S_AXI_CTRL_BUS_ADDR_WIDTH - 1:0] s_axi_CTRL_BUS_ARADDR;
output   s_axi_CTRL_BUS_RVALID;
input   s_axi_CTRL_BUS_RREADY;
output  [C_S_AXI_CTRL_BUS_DATA_WIDTH - 1:0] s_axi_CTRL_BUS_RDATA;
output  [1:0] s_axi_CTRL_BUS_RRESP;
output   s_axi_CTRL_BUS_BVALID;
input   s_axi_CTRL_BUS_BREADY;
output  [1:0] s_axi_CTRL_BUS_BRESP;
input   ap_clk;
input   ap_rst_n;
output   interrupt;
input  [15:0] in_pixel0_TDATA;
input  [0:0] in_pixel0_TLAST;
input  [15:0] in_pixel1_TDATA;
input  [0:0] in_pixel1_TLAST;
input  [15:0] in_pixel2_TDATA;
input  [0:0] in_pixel2_TLAST;
input  [15:0] in_pixel3_TDATA;
input  [0:0] in_pixel3_TLAST;
output  [15:0] out_pixel0_TDATA;
output  [0:0] out_pixel0_TLAST;
input  [15:0] in_weight0_TDATA;
input  [0:0] in_weight0_TLAST;
input   in_pixel0_TVALID;
output   in_pixel0_TREADY;
input   in_pixel1_TVALID;
output   in_pixel1_TREADY;
input   in_pixel2_TVALID;
output   in_pixel2_TREADY;
input   in_pixel3_TVALID;
output   in_pixel3_TREADY;
output   out_pixel0_TVALID;
input   out_pixel0_TREADY;
input   in_weight0_TVALID;
output   in_weight0_TREADY;

 reg    ap_rst_n_inv;
wire    ap_start;
wire    ap_ready;
wire    ap_done;
wire    ap_idle;
wire   [31:0] width;
wire   [31:0] height;
wire   [15:0] bias;
wire   [31:0] num_set;
wire   [31:0] status_i;
wire    compressed_in;
wire    compressed_out;
wire    Block_codeRepl62_pro_U0_ap_start;
wire    Block_codeRepl62_pro_U0_ap_done;
wire    Block_codeRepl62_pro_U0_ap_continue;
wire    Block_codeRepl62_pro_U0_ap_idle;
wire    Block_codeRepl62_pro_U0_ap_ready;
wire   [31:0] Block_codeRepl62_pro_U0_status_o;
wire    Block_codeRepl62_pro_U0_status_o_ap_vld;
wire   [0:0] Block_codeRepl62_pro_U0_compressed_out;
wire    Block_codeRepl62_pro_U0_in_pixel0_TREADY;
wire    Block_codeRepl62_pro_U0_in_pixel1_TREADY;
wire    Block_codeRepl62_pro_U0_in_pixel2_TREADY;
wire    Block_codeRepl62_pro_U0_in_pixel3_TREADY;
wire   [15:0] Block_codeRepl62_pro_U0_out_pixel0_TDATA;
wire    Block_codeRepl62_pro_U0_out_pixel0_TVALID;
wire   [0:0] Block_codeRepl62_pro_U0_out_pixel0_TLAST;
wire    Block_codeRepl62_pro_U0_in_weight0_TREADY;
wire   [0:0] Block_codeRepl62_pro_U0_compressed_in;
wire    ap_sync_continue;
wire    ap_sync_done;
wire    ap_sync_ready;
wire    Block_codeRepl62_pro_U0_start_full_n;
wire    Block_codeRepl62_pro_U0_start_write;

dataflow_CTRL_BUS_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_BUS_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_BUS_DATA_WIDTH ))
dataflow_CTRL_BUS_s_axi_U(
    .AWVALID(s_axi_CTRL_BUS_AWVALID),
    .AWREADY(s_axi_CTRL_BUS_AWREADY),
    .AWADDR(s_axi_CTRL_BUS_AWADDR),
    .WVALID(s_axi_CTRL_BUS_WVALID),
    .WREADY(s_axi_CTRL_BUS_WREADY),
    .WDATA(s_axi_CTRL_BUS_WDATA),
    .WSTRB(s_axi_CTRL_BUS_WSTRB),
    .ARVALID(s_axi_CTRL_BUS_ARVALID),
    .ARREADY(s_axi_CTRL_BUS_ARREADY),
    .ARADDR(s_axi_CTRL_BUS_ARADDR),
    .RVALID(s_axi_CTRL_BUS_RVALID),
    .RREADY(s_axi_CTRL_BUS_RREADY),
    .RDATA(s_axi_CTRL_BUS_RDATA),
    .RRESP(s_axi_CTRL_BUS_RRESP),
    .BVALID(s_axi_CTRL_BUS_BVALID),
    .BREADY(s_axi_CTRL_BUS_BREADY),
    .BRESP(s_axi_CTRL_BUS_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .width(width),
    .height(height),
    .bias(bias),
    .num_set(num_set),
    .status_o(Block_codeRepl62_pro_U0_status_o),
    .status_o_ap_vld(Block_codeRepl62_pro_U0_status_o_ap_vld),
    .status_i(status_i),
    .compressed_in(compressed_in),
    .compressed_out(compressed_out)
);

Block_codeRepl62_pro Block_codeRepl62_pro_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Block_codeRepl62_pro_U0_ap_start),
    .ap_done(Block_codeRepl62_pro_U0_ap_done),
    .ap_continue(Block_codeRepl62_pro_U0_ap_continue),
    .ap_idle(Block_codeRepl62_pro_U0_ap_idle),
    .ap_ready(Block_codeRepl62_pro_U0_ap_ready),
    .status_i(status_i),
    .status_o(Block_codeRepl62_pro_U0_status_o),
    .status_o_ap_vld(Block_codeRepl62_pro_U0_status_o_ap_vld),
    .width(width),
    .height(height),
    .num_set(num_set),
    .compressed_out(Block_codeRepl62_pro_U0_compressed_out),
    .in_pixel0_TDATA(in_pixel0_TDATA),
    .in_pixel0_TVALID(in_pixel0_TVALID),
    .in_pixel0_TREADY(Block_codeRepl62_pro_U0_in_pixel0_TREADY),
    .in_pixel0_TLAST(in_pixel0_TLAST),
    .in_pixel1_TDATA(in_pixel1_TDATA),
    .in_pixel1_TVALID(in_pixel1_TVALID),
    .in_pixel1_TREADY(Block_codeRepl62_pro_U0_in_pixel1_TREADY),
    .in_pixel1_TLAST(in_pixel1_TLAST),
    .in_pixel2_TDATA(in_pixel2_TDATA),
    .in_pixel2_TVALID(in_pixel2_TVALID),
    .in_pixel2_TREADY(Block_codeRepl62_pro_U0_in_pixel2_TREADY),
    .in_pixel2_TLAST(in_pixel2_TLAST),
    .in_pixel3_TDATA(in_pixel3_TDATA),
    .in_pixel3_TVALID(in_pixel3_TVALID),
    .in_pixel3_TREADY(Block_codeRepl62_pro_U0_in_pixel3_TREADY),
    .in_pixel3_TLAST(in_pixel3_TLAST),
    .out_pixel0_TDATA(Block_codeRepl62_pro_U0_out_pixel0_TDATA),
    .out_pixel0_TVALID(Block_codeRepl62_pro_U0_out_pixel0_TVALID),
    .out_pixel0_TREADY(out_pixel0_TREADY),
    .out_pixel0_TLAST(Block_codeRepl62_pro_U0_out_pixel0_TLAST),
    .in_weight0_TLAST(in_weight0_TLAST),
    .in_weight0_TVALID(in_weight0_TVALID),
    .in_weight0_TREADY(Block_codeRepl62_pro_U0_in_weight0_TREADY),
    .in_weight0_TDATA(in_weight0_TDATA),
    .compressed_in(Block_codeRepl62_pro_U0_compressed_in)
);

assign Block_codeRepl62_pro_U0_ap_continue = 1'b1;

assign Block_codeRepl62_pro_U0_ap_start = ap_start;

assign Block_codeRepl62_pro_U0_compressed_in = compressed_in;

assign Block_codeRepl62_pro_U0_compressed_out = compressed_out;

assign Block_codeRepl62_pro_U0_start_full_n = 1'b1;

assign Block_codeRepl62_pro_U0_start_write = 1'b0;

assign ap_done = Block_codeRepl62_pro_U0_ap_done;

assign ap_idle = Block_codeRepl62_pro_U0_ap_idle;

assign ap_ready = Block_codeRepl62_pro_U0_ap_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_continue = 1'b1;

assign ap_sync_done = Block_codeRepl62_pro_U0_ap_done;

assign ap_sync_ready = Block_codeRepl62_pro_U0_ap_ready;

assign in_pixel0_TREADY = Block_codeRepl62_pro_U0_in_pixel0_TREADY;

assign in_pixel1_TREADY = Block_codeRepl62_pro_U0_in_pixel1_TREADY;

assign in_pixel2_TREADY = Block_codeRepl62_pro_U0_in_pixel2_TREADY;

assign in_pixel3_TREADY = Block_codeRepl62_pro_U0_in_pixel3_TREADY;

assign in_weight0_TREADY = Block_codeRepl62_pro_U0_in_weight0_TREADY;

assign out_pixel0_TDATA = Block_codeRepl62_pro_U0_out_pixel0_TDATA;

assign out_pixel0_TLAST = Block_codeRepl62_pro_U0_out_pixel0_TLAST;

assign out_pixel0_TVALID = Block_codeRepl62_pro_U0_out_pixel0_TVALID;

endmodule //dataflow
