# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_dataflow_half_0_0/jsps_half_dataflow_half_0_0.xci
# IP: The module: 'jsps_half_dataflow_half_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_dataflow_half_0_0/constraints/dataflow_half_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'jsps_half_dataflow_half_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_dataflow_half_0_0/jsps_half_dataflow_half_0_0.xci
# IP: The module: 'jsps_half_dataflow_half_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_dataflow_half_0_0/constraints/dataflow_half_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'jsps_half_dataflow_half_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
