# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/jsps_half_smartconnect_0_0.xci
# IP: The module: 'jsps_half_smartconnect_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/bd_3f22.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_0/bd_3f22_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_1/bd_3f22_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_2/bd_3f22_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_3/bd_3f22_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_4/bd_3f22_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_5/bd_3f22_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_6/bd_3f22_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_7/bd_3f22_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_8/bd_3f22_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_9/bd_3f22_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_10/bd_3f22_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_11/bd_3f22_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_12/bd_3f22_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_13/bd_3f22_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_14/bd_3f22_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_15/bd_3f22_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_16/bd_3f22_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_17/bd_3f22_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_18/bd_3f22_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_19/bd_3f22_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_20/bd_3f22_s02mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_21/bd_3f22_s02tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_22/bd_3f22_s02sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_23/bd_3f22_s02a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_24/bd_3f22_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_25/bd_3f22_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_26/bd_3f22_s03mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_27/bd_3f22_s03tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_28/bd_3f22_s03sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_29/bd_3f22_s03a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_30/bd_3f22_sarn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_31/bd_3f22_srn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_32/bd_3f22_s04mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_33/bd_3f22_s04tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_34/bd_3f22_s04sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_35/bd_3f22_s04a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_36/bd_3f22_sarn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_37/bd_3f22_srn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_38/bd_3f22_s05mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_39/bd_3f22_s05tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_40/bd_3f22_s05sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_41/bd_3f22_s05a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_42/bd_3f22_sarn_4.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_43/bd_3f22_srn_4.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_44/bd_3f22_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_45/bd_3f22_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_46/bd_3f22_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_47/bd_3f22_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_48/bd_3f22_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_49/bd_3f22_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_50/bd_3f22_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_51/bd_3f22_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_52/bd_3f22_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_53/bd_3f22_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_54/bd_3f22_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_55/bd_3f22_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_56/bd_3f22_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_57/bd_3f22_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_58/bd_3f22_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_59/bd_3f22_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_60/bd_3f22_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_61/bd_3f22_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_62/bd_3f22_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_63/bd_3f22_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_64/bd_3f22_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_65/bd_3f22_m03s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_66/bd_3f22_m03arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_67/bd_3f22_m03rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_68/bd_3f22_m03awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_69/bd_3f22_m03wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_70/bd_3f22_m03bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_71/bd_3f22_m03e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_1/bd_3f22_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_1/bd_3f22_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_2/bd_3f22_arsw_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_3/bd_3f22_rsw_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_4/bd_3f22_awsw_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_5/bd_3f22_wsw_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_6/bd_3f22_bsw_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_10/bd_3f22_s00a2s_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_11/bd_3f22_sarn_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_12/bd_3f22_srn_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_16/bd_3f22_s01a2s_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_17/bd_3f22_sawn_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_18/bd_3f22_swn_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_19/bd_3f22_sbn_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_23/bd_3f22_s02a2s_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_24/bd_3f22_sarn_1_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_25/bd_3f22_srn_1_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_29/bd_3f22_s03a2s_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_30/bd_3f22_sarn_2_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_31/bd_3f22_srn_2_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_35/bd_3f22_s04a2s_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_36/bd_3f22_sarn_3_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_37/bd_3f22_srn_3_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_41/bd_3f22_s05a2s_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_42/bd_3f22_sarn_4_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_43/bd_3f22_srn_4_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_44/bd_3f22_m00s2a_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_45/bd_3f22_m00arn_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_46/bd_3f22_m00rn_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_47/bd_3f22_m00awn_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_48/bd_3f22_m00wn_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_49/bd_3f22_m00bn_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_51/bd_3f22_m01s2a_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_52/bd_3f22_m01arn_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_53/bd_3f22_m01rn_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_54/bd_3f22_m01awn_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_55/bd_3f22_m01wn_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_56/bd_3f22_m01bn_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_58/bd_3f22_m02s2a_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_59/bd_3f22_m02arn_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_60/bd_3f22_m02rn_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_61/bd_3f22_m02awn_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_62/bd_3f22_m02wn_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_63/bd_3f22_m02bn_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_65/bd_3f22_m03s2a_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_66/bd_3f22_m03arn_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_67/bd_3f22_m03rn_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_68/bd_3f22_m03awn_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_69/bd_3f22_m03wn_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_70/bd_3f22_m03bn_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'jsps_half_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/jsps_half_smartconnect_0_0.xci
# IP: The module: 'jsps_half_smartconnect_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/bd_3f22.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_0/bd_3f22_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_1/bd_3f22_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_2/bd_3f22_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_3/bd_3f22_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_4/bd_3f22_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_5/bd_3f22_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_6/bd_3f22_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_7/bd_3f22_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_8/bd_3f22_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_9/bd_3f22_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_10/bd_3f22_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_11/bd_3f22_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_12/bd_3f22_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_13/bd_3f22_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_14/bd_3f22_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_15/bd_3f22_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_16/bd_3f22_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_17/bd_3f22_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_18/bd_3f22_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_19/bd_3f22_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_20/bd_3f22_s02mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_21/bd_3f22_s02tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_22/bd_3f22_s02sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_23/bd_3f22_s02a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_24/bd_3f22_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_25/bd_3f22_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_26/bd_3f22_s03mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_27/bd_3f22_s03tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_28/bd_3f22_s03sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_29/bd_3f22_s03a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_30/bd_3f22_sarn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_31/bd_3f22_srn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_32/bd_3f22_s04mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_33/bd_3f22_s04tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_34/bd_3f22_s04sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_35/bd_3f22_s04a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_36/bd_3f22_sarn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_37/bd_3f22_srn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_38/bd_3f22_s05mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_39/bd_3f22_s05tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_40/bd_3f22_s05sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_41/bd_3f22_s05a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_42/bd_3f22_sarn_4.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_43/bd_3f22_srn_4.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_44/bd_3f22_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_45/bd_3f22_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_46/bd_3f22_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_47/bd_3f22_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_48/bd_3f22_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_49/bd_3f22_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_50/bd_3f22_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_51/bd_3f22_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_52/bd_3f22_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_53/bd_3f22_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_54/bd_3f22_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_55/bd_3f22_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_56/bd_3f22_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_57/bd_3f22_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_58/bd_3f22_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_59/bd_3f22_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_60/bd_3f22_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_61/bd_3f22_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_62/bd_3f22_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_63/bd_3f22_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_64/bd_3f22_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_65/bd_3f22_m03s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_66/bd_3f22_m03arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_67/bd_3f22_m03rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_68/bd_3f22_m03awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_69/bd_3f22_m03wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_70/bd_3f22_m03bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_71/bd_3f22_m03e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_1/bd_3f22_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_1/bd_3f22_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_2/bd_3f22_arsw_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_3/bd_3f22_rsw_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_4/bd_3f22_awsw_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_5/bd_3f22_wsw_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_6/bd_3f22_bsw_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_10/bd_3f22_s00a2s_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_11/bd_3f22_sarn_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_12/bd_3f22_srn_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_16/bd_3f22_s01a2s_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_17/bd_3f22_sawn_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_18/bd_3f22_swn_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_19/bd_3f22_sbn_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_23/bd_3f22_s02a2s_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_24/bd_3f22_sarn_1_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_25/bd_3f22_srn_1_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_29/bd_3f22_s03a2s_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_30/bd_3f22_sarn_2_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_31/bd_3f22_srn_2_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_35/bd_3f22_s04a2s_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_36/bd_3f22_sarn_3_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_37/bd_3f22_srn_3_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_41/bd_3f22_s05a2s_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_42/bd_3f22_sarn_4_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_43/bd_3f22_srn_4_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_44/bd_3f22_m00s2a_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_45/bd_3f22_m00arn_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_46/bd_3f22_m00rn_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_47/bd_3f22_m00awn_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_48/bd_3f22_m00wn_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_49/bd_3f22_m00bn_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_51/bd_3f22_m01s2a_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_52/bd_3f22_m01arn_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_53/bd_3f22_m01rn_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_54/bd_3f22_m01awn_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_55/bd_3f22_m01wn_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_56/bd_3f22_m01bn_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_58/bd_3f22_m02s2a_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_59/bd_3f22_m02arn_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_60/bd_3f22_m02rn_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_61/bd_3f22_m02awn_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_62/bd_3f22_m02wn_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_63/bd_3f22_m02bn_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_65/bd_3f22_m03s2a_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_66/bd_3f22_m03arn_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_67/bd_3f22_m03rn_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_68/bd_3f22_m03awn_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_69/bd_3f22_m03wn_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/bd_0/ip/ip_70/bd_3f22_m03bn_0_ooc.xdc

# XDC: c:/Users/vpanchbhaiyye/Documents/jsps_half/jsps_half.srcs/sources_1/bd/jsps_half/ip/jsps_half_smartconnect_0_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'jsps_half_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
